### PR TITLE
Form Validation

### PR DESCRIPTION
**Pull request by Uchenna-ibute**
1. The content of the email field has to be in lowercase.
2. When the user submits the form, it checks if the email is in lowercase.
3. If the validation is OK, the form is sent.
4. If the validation is not OK, it shows an error message to the user near the submit button informing them of the error, and the form is not sent.

### CODE REVIEW

**Comment by Kingno3l** [comment]
Congratulations.

Well done!

**Review by leonardodiasb — APPROVED** [review]
# Status: ✔️ Project Approved ✔️ 

Hi @Kingno3l,

Everything is looking great! Please, merge this branch :shipit:
Congratulations! 🎉

## Highlights

 - Professional PR and README. ✔️
 - Nice UI design. ✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Nemwel-Boniface** [comment]
## Hello team :wave: ,
I am Nemwel your reviewer for this PR :man_beard: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## :heavy_multiplication_x:  Invalid Code Review Request :heavy_multiplication_x: 

You have submitted a project, that has no passing linters. KIndly ensure that they are passing before resubmitting for review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by brainconnect93 — COMMENTED** [review]
Hi @Kingno3l, 👋 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.



## Invalid Code Review Request

- [x] You have submitted a project, that has no passing linters. Kindly ensure that they are passing before resubmitting for review.

- [x] Kindly create a new pull request for the new submission of this project with your partner as I notice you submitting a merged pull request.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

_Cheers and Happy coding!👏👏👏_

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

-----

_Invalid Code Review Request does not count into the code reviews limit._

**Comment by Kingno3l** [comment]
this pull request was approved last week.
I repeated the week and have to submit it again.
kindly approve.

**Review by HAMMAS-SALEEM — COMMENTED** [review]
# Important Note (For Future) 🔈

### This is a pair-programming project where each student needs to submit his/her own pull request. If in future you face the same situation with one difference which is that you have to submit your pull request on behalf of your coding partner group, so in that case you will need to make a new pull request everything for start 🤔

# Status: Approved :green_circle: :1st_place_medal: :100:
success

### Hey @Uchenna-ibute 👋

Great work on implementing the requirements. Your project is complete. :blush:
There is nothing else to say about your project. :+1:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Requirements
✔️ Following Linters

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by nicupop729** [comment]
Hi @Kingno3l,

Kindly note that this PR was approved for this block only because even though is a pair-programming activity, each student in the pair-programming group needs to submit the Code Review Requests individually.

In the case of pair-programming activities where 1 student submits in the name of the entire group, the CRs cannot reapprove PRs from previous weeks.

**Pull request merged**
